# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 2503667cca92b57e1e251eb109e6ee4b6759e72bd52412ffe1bb78a0418b495103c858430684c70ceb6814713cd26de9705f5028621a24ff231ad67b333e0729

test:
  secret_key_base: e29680a8c956fb05fcf46c337b8669cf34ec7a058d19e83a59cc9713099d286e65f4b9e84a5130c9d7b067161f6b38988ea4d1c16cfdddc7a0ca87fea5b76d24

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
